import type { TShirtTemplate, Fabric } from '../types';

export const templates: TShirtTemplate[] = [
  {
    id: 'tpl-001',
    name: 'Classic Minimal',
    category: 'Minimal',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80',
    previewColors: ['#FFFFFF', '#111111', '#E5E5E5'],
    style: 'crew',
    gender: 'unisex',
    tags: ['minimal', 'classic', 'everyday'],
  },
  {
    id: 'tpl-002',
    name: 'Urban Street',
    category: 'Streetwear',
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80',
    previewColors: ['#1A1A1A', '#4A4A4A', '#F5F5F5'],
    style: 'oversized',
    gender: 'unisex',
    tags: ['urban', 'street', 'oversized'],
  },
  {
    id: 'tpl-003',
    name: 'Fitted Essential',
    category: 'Basics',
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80',
    previewColors: ['#FFFFFF', '#C9B8A8', '#8B7355'],
    style: 'fitted',
    gender: 'women',
    tags: ['fitted', 'essential', 'feminine'],
  },
  {
    id: 'tpl-004',
    name: 'V-Neck Premium',
    category: 'Premium',
    image: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=600&q=80',
    previewColors: ['#F5F0EB', '#D4C5B2', '#2C2C2C'],
    style: 'v-neck',
    gender: 'men',
    tags: ['premium', 'v-neck', 'smart casual'],
  },
  {
    id: 'tpl-005',
    name: 'Polo Sport',
    category: 'Sport',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80',
    previewColors: ['#FFFFFF', '#1B4F72', '#196F3D'],
    style: 'polo',
    gender: 'unisex',
    tags: ['polo', 'sport', 'preppy'],
  },
  {
    id: 'tpl-006',
    name: 'Artist Canvas',
    category: 'Art',
    image: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600&q=80',
    previewColors: ['#FFF9F0', '#F0EAD6', '#E8D5B7'],
    style: 'crew',
    gender: 'unisex',
    tags: ['art', 'creative', 'expressive'],
  },
  {
    id: 'tpl-007',
    name: 'Vintage Wash',
    category: 'Vintage',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80',
    previewColors: ['#D4A574', '#C89B6E', '#B08850'],
    style: 'crew',
    gender: 'unisex',
    tags: ['vintage', 'retro', 'washed'],
  },
  {
    id: 'tpl-008',
    name: 'Luxe Drape',
    category: 'Luxury',
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&q=80',
    previewColors: ['#1A1A2E', '#16213E', '#0F3460'],
    style: 'oversized',
    gender: 'women',
    tags: ['luxury', 'premium', 'elegant'],
  },
];

export const fabrics: Fabric[] = [
  {
    id: 'fab-001',
    name: '100% Organic Cotton',
    composition: '100% GOTS Certified Organic Cotton',
    weight: '180 GSM',
    feel: 'Soft, breathable, natural',
    careInstructions: ['Machine wash 30°C', 'Tumble dry low', 'Do not bleach'],
    priceMultiplier: 1.0,
    recommended: true,
    colors: [
      { id: 'c1', name: 'White', hex: '#FFFFFF', available: true },
      { id: 'c2', name: 'Black', hex: '#111111', available: true },
      { id: 'c3', name: 'Navy', hex: '#1B2A4A', available: true },
      { id: 'c4', name: 'Stone', hex: '#C9B8A8', available: true },
      { id: 'c5', name: 'Sage', hex: '#87A878', available: true },
      { id: 'c6', name: 'Dusty Rose', hex: '#D4A5A5', available: true },
    ],
  },
  {
    id: 'fab-002',
    name: 'Cotton-Modal Blend',
    composition: '60% Cotton, 40% Modal',
    weight: '160 GSM',
    feel: 'Ultra-soft, silky, drapes beautifully',
    careInstructions: ['Machine wash 30°C', 'Hang dry', 'Iron low heat'],
    priceMultiplier: 1.3,
    recommended: false,
    colors: [
      { id: 'c7', name: 'Ivory', hex: '#FFFFF0', available: true },
      { id: 'c8', name: 'Charcoal', hex: '#36454F', available: true },
      { id: 'c9', name: 'Blush', hex: '#FFB6C1', available: true },
      { id: 'c10', name: 'Slate', hex: '#708090', available: true },
    ],
  },
  {
    id: 'fab-003',
    name: 'Performance Dry-Fit',
    composition: '88% Polyester, 12% Elastane',
    weight: '140 GSM',
    feel: 'Moisture-wicking, stretchy, athletic',
    careInstructions: ['Machine wash 40°C', 'Do not tumble dry', 'Do not iron print'],
    priceMultiplier: 1.2,
    recommended: false,
    colors: [
      { id: 'c11', name: 'White', hex: '#FFFFFF', available: true },
      { id: 'c12', name: 'Black', hex: '#111111', available: true },
      { id: 'c13', name: 'Royal Blue', hex: '#4169E1', available: true },
      { id: 'c14', name: 'Red', hex: '#CC0000', available: true },
    ],
  },
  {
    id: 'fab-004',
    name: 'French Terry',
    composition: '80% Cotton, 20% Polyester',
    weight: '240 GSM',
    feel: 'Plush, warm, comfortable',
    careInstructions: ['Machine wash 40°C', 'Tumble dry medium', 'Do not bleach'],
    priceMultiplier: 1.4,
    recommended: false,
    colors: [
      { id: 'c15', name: 'Ecru', hex: '#F5F0E8', available: true },
      { id: 'c16', name: 'Mocha', hex: '#6F4E37', available: true },
      { id: 'c17', name: 'Forest', hex: '#228B22', available: true },
    ],
  },
  {
    id: 'fab-005',
    name: 'Bamboo Viscose',
    composition: '70% Bamboo Viscose, 30% Cotton',
    weight: '170 GSM',
    feel: 'Eco-friendly, antibacterial, gentle on skin',
    careInstructions: ['Hand wash cold', 'Hang dry', 'Do not wring'],
    priceMultiplier: 1.5,
    recommended: false,
    colors: [
      { id: 'c18', name: 'White', hex: '#FFFFFF', available: true },
      { id: 'c19', name: 'Soft Grey', hex: '#D3D3D3', available: true },
      { id: 'c20', name: 'Mint', hex: '#98FF98', available: true },
    ],
  },
];

export const BASE_PRICE = 599;

export const categories = ['All', 'Minimal', 'Streetwear', 'Basics', 'Premium', 'Sport', 'Art', 'Vintage', 'Luxury'];

export const colorPalettes = [
  {
    name: 'Earth Tones',
    colors: ['#C9B8A8', '#A0876E', '#8B6914', '#6B4F3A', '#F5EDE0'],
    mood: 'Natural & Organic',
  },
  {
    name: 'Ocean Blues',
    colors: ['#E8F4FD', '#A8D8EA', '#5BA4CF', '#1B4F72', '#0D2137'],
    mood: 'Fresh & Calming',
  },
  {
    name: 'Monochrome',
    colors: ['#FFFFFF', '#D0D0D0', '#888888', '#444444', '#111111'],
    mood: 'Classic & Timeless',
  },
  {
    name: 'Sunset',
    colors: ['#FFF3E0', '#FFCC80', '#FFA726', '#E65100', '#BF360C'],
    mood: 'Warm & Energetic',
  },
  {
    name: 'Forest',
    colors: ['#F1F8E9', '#AED581', '#66BB6A', '#2E7D32', '#1B5E20'],
    mood: 'Nature & Calm',
  },
  {
    name: 'Lavender Dreams',
    colors: ['#F3E5F5', '#CE93D8', '#AB47BC', '#7B1FA2', '#4A148C'],
    mood: 'Dreamy & Creative',
  },
];
